language: csharp
solution: "./CodeInterview.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./CodeInterview.sln
script:
- xbuild ./CodeInterview.sln
- mono ./lib/xunit/xunit.console.clr4.x86.exe CodeInterview.WeatherDress.Core.Tests/bin/Debug/CodeInterview.WeatherDress.Core.Tests.dll