// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CodeInterview.WeatherDress.Core.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class InvalidWeatherDressingFeature : Xunit.IClassFixture<InvalidWeatherDressingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InvalidWeatherDressup.feature"
#line hidden
        
        public InvalidWeatherDressingFeature(InvalidWeatherDressingFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "InvalidWeatherDressing", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Duplicate DressOn")]
        [Xunit.TraitAttribute("FeatureTitle", "InvalidWeatherDressing")]
        [Xunit.TraitAttribute("Description", "Duplicate DressOn")]
        [Xunit.TraitAttribute("Category", "integration")]
        public virtual void DuplicateDressOn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate DressOn", new string[] {
                        "integration"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("the weather is \"HOT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dress"});
            table1.AddRow(new string[] {
                        "Pajamas_Off"});
            table1.AddRow(new string[] {
                        "PantsOn"});
            table1.AddRow(new string[] {
                        "PantsOn"});
#line 9
 testRunner.When("I wear the following in the given order", ((string)(null)), table1, "When ");
#line 14
 testRunner.Then("the dressing should fail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Dress with Socks in Hot Weather")]
        [Xunit.TraitAttribute("FeatureTitle", "InvalidWeatherDressing")]
        [Xunit.TraitAttribute("Description", "Dress with Socks in Hot Weather")]
        [Xunit.TraitAttribute("Category", "integration")]
        public virtual void DressWithSocksInHotWeather()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dress with Socks in Hot Weather", new string[] {
                        "integration"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("the weather is \"HOT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dress"});
            table2.AddRow(new string[] {
                        "Pajamas_Off"});
            table2.AddRow(new string[] {
                        "PantsOn"});
            table2.AddRow(new string[] {
                        "SocksOn"});
#line 19
 testRunner.When("I wear the following in the given order", ((string)(null)), table2, "When ");
#line 24
 testRunner.Then("the dressing should fail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Dress with Jacket in Hot Weather")]
        [Xunit.TraitAttribute("FeatureTitle", "InvalidWeatherDressing")]
        [Xunit.TraitAttribute("Description", "Dress with Jacket in Hot Weather")]
        [Xunit.TraitAttribute("Category", "integration")]
        public virtual void DressWithJacketInHotWeather()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dress with Jacket in Hot Weather", new string[] {
                        "integration"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("the weather is \"HOT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dress"});
            table3.AddRow(new string[] {
                        "Pajamas_Off"});
            table3.AddRow(new string[] {
                        "PantsOn"});
            table3.AddRow(new string[] {
                        "ShirtOn"});
            table3.AddRow(new string[] {
                        "HeadwearOn"});
            table3.AddRow(new string[] {
                        "JacketOn"});
            table3.AddRow(new string[] {
                        "FootwearOn"});
            table3.AddRow(new string[] {
                        "LeaveHouse"});
#line 29
 testRunner.When("I wear the following in the given order", ((string)(null)), table3, "When ");
#line 38
 testRunner.Then("the dressing should fail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="No Complete Dressing (miss to wear atleast one dressing)")]
        [Xunit.TraitAttribute("FeatureTitle", "InvalidWeatherDressing")]
        [Xunit.TraitAttribute("Description", "No Complete Dressing (miss to wear atleast one dressing)")]
        [Xunit.TraitAttribute("Category", "integration")]
        public virtual void NoCompleteDressingMissToWearAtleastOneDressing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No Complete Dressing (miss to wear atleast one dressing)", new string[] {
                        "integration"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("the weather is \"HOT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dress"});
            table4.AddRow(new string[] {
                        "Pajamas_Off"});
            table4.AddRow(new string[] {
                        "PantsOn"});
            table4.AddRow(new string[] {
                        "ShirtOn"});
            table4.AddRow(new string[] {
                        "HeadwearOn"});
            table4.AddRow(new string[] {
                        "JacketOn"});
            table4.AddRow(new string[] {
                        "FootwearOn"});
            table4.AddRow(new string[] {
                        "LeaveHouse"});
#line 43
 testRunner.When("I wear the following in the given order", ((string)(null)), table4, "When ");
#line 52
 testRunner.Then("the dressing should fail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Dress without PajamasOff")]
        [Xunit.TraitAttribute("FeatureTitle", "InvalidWeatherDressing")]
        [Xunit.TraitAttribute("Description", "Dress without PajamasOff")]
        [Xunit.TraitAttribute("Category", "integration")]
        public virtual void DressWithoutPajamasOff()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dress without PajamasOff", new string[] {
                        "integration"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("the weather is \"HOT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dress"});
            table5.AddRow(new string[] {
                        "Pajamas_Off"});
            table5.AddRow(new string[] {
                        "PantsOn"});
            table5.AddRow(new string[] {
                        "ShirtOn"});
            table5.AddRow(new string[] {
                        "HeadwearOn"});
            table5.AddRow(new string[] {
                        "JacketOn"});
            table5.AddRow(new string[] {
                        "FootwearOn"});
            table5.AddRow(new string[] {
                        "LeaveHouse"});
#line 57
 testRunner.When("I wear the following in the given order", ((string)(null)), table5, "When ");
#line 66
 testRunner.Then("the dressing should fail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                InvalidWeatherDressingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                InvalidWeatherDressingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
